name: Generate Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at 00:00 UTC
  workflow_dispatch:       # lets you run it manually in Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Generate the SVG snake from your contributions
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: arsh-911
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Publish to "output" branch so the README can reference a stable raw URL
      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
