name: Generate Snake Animation

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  
  # allows manual run from Actions tab
  workflow_dispatch:
  
  # run on every push to main branch
  push:
    branches:
    - main
    - master

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      
      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: arsh-911
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
            dist/ocean.gif
      
      # Push the generated files to output branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
